### ISSUE TITLE
requirements.txt file missing

### ISSUE THREAD

**Issue by joaomj** [lloydhamilton/aws_lambdas_deploy#1]
Hi Lloyd!

I am currently learning through your tutorial on [Toward Data Science](https://towardsdatascience.com/serverless-deployment-of-machine-learning-models-on-aws-lambda-5bd1ca9b5c42). Its amazing and detailed!

In the "Pre-requisites", item 10, you list some Python libraries used in this project and said "**_alternatively the requirements.txt file is included in the Git repository_**" but i could not find this file here.

Can you include the requirements.txt file on this repo?

Thank you for your help.

**Comment by lloydhamilton** [comment]
Hi Joao!

Thanks. I am happy you liked it. More than happy to assist you in any way. 
Sorry for the error on my part. I have pushed the requirements.txt file as requested.

Regards,
Lloyd Hamilton
